# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/fastgitorg/fgit-go
    environment:
      CGO_ENABLED: "0"
    steps:
      - checkout
      - run:
          name:
            Build AMD64
          command: |
            GOARCH=amd64 GOOS=windows go build -ldflags "-s -w" -o ~/release/fgit-windows-amd64.exe src/fgit.go 
            GOARCH=amd64 GOOS=darwin go build -ldflags "-s -w" -o ~/release/fgit-darwin-amd64 src/fgit.go 
            GOARCH=amd64 GOOS=linux go build -ldflags "-s -w" -o ~/release/fgit-linux-amd64 src/fgit.go 

      - run:
          name:
            Build 386
          command: |
            GOARCH=386 GOOS=windows go build -ldflags "-s -w" -o ~/release/fgit-windows-386.exe src/fgit.go 
            GOARCH=386 GOOS=linux go build -ldflags "-s -w" -o ~/release/fgit-linux-386 src/fgit.go 

      - run:
          name:
            Build ARM
          command: |
            GOARCH=arm GOOS=linux go build -ldflags "-s -w" -o ~/release/fgit-linux-arm src/fgit.go 

      - run:
          name:
            Build ARM64
          command: |
            GOARCH=arm64 GOOS=linux go build -ldflags "-s -w" -o ~/release/fgit-linux-arm64 src/fgit.go 
              
      - store_artifacts:
          path: ~/release
          destination: CI Build
