# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/fastgitorg/fgit-go
    environment:
      CGO_ENABLED: "0"
    steps:
      - checkout
      - run:
          name:
            Build AMD64
          command: |
            version=`cat version`
            timestamp=`date "+%Y-%m-%d %H:%M:%S"`
            echo "version -> $version"
            echo "timestamp -> $timestamp"
            GOARCH=amd64 GOOS=windows go build -ldflags "-s -w -X main.version=$version -X \"main.timestamp=$timestamp\"" -o ~/release/fgit-windows-amd64.exe .\src
            GOARCH=amd64 GOOS=darwin go build -ldflags "-s -w -X main.version=$version -X \"main.timestamp=$timestamp\"" -o ~/release/fgit-darwin-amd64 ./src
            GOARCH=amd64 GOOS=linux go build -ldflags "-s -w -X main.version=$version -X \"main.timestamp=$timestamp\"" -o ~/release/fgit-linux-amd64 ./src

      - run:
          name:
            Build 386
          command: |
            version=`cat version`
            timestamp=`date "+%Y-%m-%d %H:%M:%S"`
            echo "version -> $version"
            echo "timestamp -> $timestamp"
            GOARCH=386 GOOS=windows go build -ldflags "-s -w -X main.version=$version -X \"main.timestamp=$timestamp\"" -o ~/release/fgit-windows-386.exe .\src
            GOARCH=386 GOOS=linux go build -ldflags "-s -w -X main.version=$version -X \"main.timestamp=$timestamp\"" -o ~/release/fgit-linux-386 ./src

      - run:
          name:
            Build ARM
          command: |
            version=`cat version`
            timestamp=`date "+%Y-%m-%d %H:%M:%S"`
            echo "version -> $version"
            echo "timestamp -> $timestamp"
            GOARCH=arm GOOS=linux go build -ldflags "-s -w -X main.version=$version -X \"main.timestamp=$timestamp\"" -o ~/release/fgit-linux-arm ./src

      - run:
          name:
            Build ARM64
          command: |
            version=`cat version`
            timestamp=`date "+%Y-%m-%d %H:%M:%S"`
            echo "version -> $version"
            echo "timestamp -> $timestamp"
            GOARCH=arm64 GOOS=linux go build -ldflags "-s -w -X main.version=$version -X \"main.timestamp=$timestamp\"" -o ~/release/fgit-linux-arm64 ./src

      - run:
          name:
            Archive
          command: |
            mkdir ~/tmp
            tar -zcvf ~/tmp/all.tar.gz ~/release
            cp ~/tmp/all.tar.gz ~/release

      - store_artifacts:
          path: ~/release
          destination: CI Build
