# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/fastgitorg/fgit-go
    environment:
      CGO_ENABLED: 0
    steps:
      - checkout
      - run:
          name:
            Build AMD64
          command: |
            GOARCH=amd64
            GOOS=windows
            go build -o ~/release/fgit-windows-amd64.exe fgit.go
            GOOS=darwin
            go build -o ~/release/fgit-darwin-amd64 fgit.go
            GOOS=linux
            go build -o ~/release/fgit-linux-amd64 fgit.go

      - run:
          name:
            Build 386
          command: |
            GOARCH=386
            GOOS=windows
            go build -o ~/release/fgit-windows-386.exe fgit.go
            GOOS=linux
            go build -o ~/release/fgit-linux-386 fgit.go

      - run:
          name:
            Build ARM
          command: |
            GOARCH=arm
            GOOS=linux
            go build -o ~/release/fgit-linux-arm fgit.go

      - run:
          name:
            Build ARM64
          command: |
            GOARCH=arm64
            GOOS=linux
            go build -o ~/release/fgit-linux-arm64 fgit.go
              
      - store_artifacts:
          path: ~/release
          destination: CI Build
